SELECT
  (SELECT CODEMP FROM TSIEMP EMP WHERE A.CODEMP_ANP = EMP.AD_CODEMP_ANP) AS CODEMP,
  COALESCE(A.CODPROD_ANP,'0') AS CODPROD_ANP,
  (SELECT DISTINCT DESCRANP FROM TGFPRO PRO WHERE A.CODPROD_ANP = PRO.CODANP AND ROWNUM <= 1) AS DESCR_PROD,
  COALESCE(A.QTD_PROD_UN_ANP,'0') AS QTD_PROD_UN_ANP,
  B.MES_REFERENCIA,
  B.ANO_REFRENCIA,
  (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'OPERPADESTINICI') AS OPER_INI
FROM AD_DETSIMULARSIMP A
INNER JOIN AD_SIMULARSIMP B ON A.CODSIMSIM = B.CODSIMSIM
WHERE A.CODSIMSIM = ?
  AND A.CODOPER = (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'OPERPADESTFINAL')
ORDER BY A.CODDETSIMSIMP
