SELECT DISTINCT
  (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'OPERPADESTINICI') AS OPERACAO,
  COALESCE(F.AD_CODEMP_ANP,'0') AS AD_CODEMP_ANP,
  COALESCE(F.AD_CODINSTALACAO_ANP,'0') AS COD_INST_EMP,
  '0' AS COD_INST_PAR,
  TO_CHAR(COALESCE(E.CODANP,0)) AS CODPROD_ANP,
  0 AS QTD_UN_PADRAO,
  0 AS QTD_CONVERTIDO_KG,
  '1' AS CODMODAL_SIMP,
  '0' AS COD_OLEODUTO,
  '0' AS CNPJ_PARC,
  '0' AS CODCID_ANP,
  '0' AS AD_CNAE_ANP,
  '0' AS COD_PAIS_ANP,
  '0' AS LICENCA_IMPORTACAO_LI,
  '0' AS NUM_DELCARACAO_IMPORTACAO_DI,
  '0' AS NRONF,
  '0' AS COD_SERIE_NF,
  '0' AS DTENTSAI,
  '0' AS COD_TIP_TAR_SERV,
  '0' AS CARACTERISTICA_INATIVO,
  '0' AS METODO_INATIVO,
  0 AS MODALIDADE_FRETE,
  '0' AS VALOR_CARACTERISTICA,
  0 AS CODPROD_RESULTANTE_ANP,
  A.vlrunit AS VLRUNIT,
  '0' AS RECIPIENTE_GLP,
  '0' AS CHAVE_NFE_CTE,
  0 AS OPER_TOTALIZADOR
FROM TGFITE A
INNER JOIN TGFCAB B ON A.NUNOTA = B.NUNOTA
INNER JOIN TGFTOP C ON B.CODTIPOPER = C.CODTIPOPER
  AND C.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP TOP WHERE C.CODTIPOPER = TOP.CODTIPOPER)
INNER JOIN TGFPAR D ON B.CODPARC = D.CODPARC
INNER JOIN TGFPRO E ON A.CODPROD = E.CODPROD
INNER JOIN TSIEMP F ON B.CODEMP = F.CODEMP
WHERE COALESCE(C.AD_ATUALIZA_EST_SIMP,'N') = 'S'
  AND COALESCE(E.AD_GERA_SIMP,'N') = 'S'
  AND TO_CHAR(B.DTNEG,'mm-yyyy') = ?
  AND B.CODEMP = ?
  AND CODANP NOT IN (
      SELECT COALESCE(ESTDET.CODANP,'0')
      FROM AD_IMPORTADORESTOQUESIMPCAB ESTCAB
      INNER JOIN AD_IMPORTADORESTOQUESIMPDET ESTDET ON ESTCAB.CODIMPDOCCAB = ESTDET.CODIMPDOCCAB
      WHERE TO_DATE('01'||'/'||(LPAD(ESTCAB.MES,2,0)||'/'||ESTCAB.ANO),'dd/mm/yyyy') = (
              SELECT MAX(TO_DATE('01'||'/'||(LPAD(CAB.MES,2,0)||'/'||CAB.ANO),'dd/mm/yyyy'))
              FROM AD_IMPORTADORESTOQUESIMPCAB CAB
              WHERE CAB.MES IS NOT NULL AND CAB.ANO IS NOT NULL
          )
        AND COALESCE(CODEMP,1) = ?
        AND ESTDET.CODANP IS NOT NULL
  )
