SELECT
  COALESCE(ESTDET.CODOPER,(SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'OPERPADESTINICI')) AS OPERACAO,
  COALESCE((SELECT AD_CODEMP_ANP FROM TSIEMP WHERE CODEMP = COALESCE(ESTDET.CODEMP,1)),'0') AS AD_CODEMP_ANP,
  COALESCE((SELECT AD_CODINSTALACAO_ANP FROM TSIEMP WHERE CODEMP = COALESCE(ESTDET.CODEMP,1)),'0') AS COD_INST_EMP,
  '0' AS COD_INST_PAR,
  COALESCE(ESTDET.CODANP,'0') AS CODPROD_ANP,
  COALESCE(ESTDET.QTDE,0) AS QTD_UN_PADRAO,
  COALESCE(ESTDET.QTDE,0) AS QTD_CONVERTIDO_KG,
  '1' AS CODMODAL_SIMP,
  '0' AS COD_OLEODUTO,
  '0' AS CNPJ_PARC,
  '0' AS CODCID_ANP,
  '0' AS AD_CNAE_ANP,
  '0' AS COD_PAIS_ANP,
  '0' AS LICENCA_IMPORTACAO_LI,
  '0' AS NUM_DELCARACAO_IMPORTACAO_DI,
  '0' AS NRONF,
  '0' AS COD_SERIE_NF,
  '0' AS DTENTSAI,
  '0' AS COD_TIP_TAR_SERV,
  '0' AS CARACTERISTICA_INATIVO,
  '0' AS METODO_INATIVO,
  0 AS MODALIDADE_FRETE,
  '0' AS VALOR_CARACTERISTICA,
  0 AS CODPROD_RESULTANTE_ANP,
  0 AS VLRUNIT,
  '0' AS RECIPIENTE_GLP,
  '0' AS CHAVE_NFE_CTE,
  0 AS OPER_TOTALIZADOR
FROM AD_IMPORTADORESTOQUESIMPCAB ESTCAB
INNER JOIN AD_IMPORTADORESTOQUESIMPDET ESTDET ON ESTCAB.CODIMPDOCCAB = ESTDET.CODIMPDOCCAB
WHERE TO_DATE('01'||'/'||(LPAD(ESTCAB.MES,2,0)||'/'||ESTCAB.ANO),'dd/mm/yyyy') = (
        SELECT MAX(TO_DATE('01'||'/'||(LPAD(CAB.MES,2,0)||'/'||CAB.ANO),'dd/mm/yyyy'))
        FROM AD_IMPORTADORESTOQUESIMPCAB CAB
        WHERE CAB.MES IS NOT NULL AND CAB.ANO IS NOT NULL
      )
  AND COALESCE(CODEMP,1) = ?
