SELECT
  NUNOTA,
  LISTAGG(SEQUENCIA,',') AS SEQUENCIA,
  LISTAGG(CODPROD,',') AS CODPROD,
  AD_TEM_COLETA,
  OPER_PAD_DISP_COLETA,
  CLASS_OPERACAO,
  OPERACAO,
  AD_CODEMP_ANP,
  COD_INST_EMP,
  COD_INST_PAR,
  CODPROD_ANP,
  SUM(TO_NUMBER(COALESCE(QTD_UN_PADRAO,0))) AS QTD_UN_PADRAO,
  SUM(TO_NUMBER(COALESCE(QTD_CONVERTIDO_KG,0))) AS QTD_CONVERTIDO_KG,
  CODMODAL_SIMP,
  COD_OLEODUTO,
  CNPJ_PARC,
  (CASE WHEN COALESCE(CNPJ_PARC,'0') = '0' AND COALESCE(AD_TEM_COLETA,'N') = 'N' THEN '0' ELSE CODCID_ANP END) AS CODCID_ANP,
  AD_CNAE_ANP,
  COD_PAIS_ANP,
  LICENCA_IMPORTACAO_LI,
  NUM_DELCARACAO_IMPORTACAO_DI,
  NRONF,
  COD_SERIE_NF,
  DTENTSAI,
  COD_TIP_TAR_SERV,
  CARACTERISTICA_INATIVO,
  METODO_INATIVO,
  MODALIDADE_FRETE,
  VALOR_CARACTERISTICA,
  CODPROD_RESULTANTE_ANP,
  VLRUNIT,
  RECIPIENTE_GLP,
  CHAVE_NFE_CTE,
  OPER_TOTALIZADOR
FROM(
  SELECT
    A.NUNOTA,
    A.SEQUENCIA,
    A.CODPROD,
    COALESCE(E.AD_TEM_COLETA,'N') AS AD_TEM_COLETA,
    (SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'OPERDISPCOLETA') AS OPER_PAD_DISP_COLETA,
    (SELECT CLASSE FROM AD_OPERACAOANP OPER WHERE OPER.CODOPER = C.AD_CODOPERANP) AS CLASS_OPERACAO,
    (CASE WHEN D.AD_CODINSTALACAO_ANP IS NOT NULL THEN C.AD_CODOPERANP ELSE C.AD_CODOPERANPAGENTENREGULADO END) AS OPERACAO,
    COALESCE(F.AD_CODEMP_ANP,'0') AS AD_CODEMP_ANP,
    COALESCE(F.AD_CODINSTALACAO_ANP,'0') AS COD_INST_EMP,
    COALESCE(D.AD_CODINSTALACAO_ANP,'0') AS COD_INST_PAR,
    TO_CHAR(COALESCE(E.CODANP,0)) AS CODPROD_ANP,
    COALESCE((
      CASE WHEN E.CODVOL IN ('LT','KG') THEN A.QTDNEG
           WHEN E.PESOLIQ != 0 THEN E.PESOLIQ * QTDNEG
           WHEN E.CODVOL != 'LT' AND E.PESOLIQ = 0 AND EXISTS (SELECT * FROM TGFVOA VOA WHERE VOA.CODVOL ='LT' AND A.CODPROD = VOA.CODPROD)
                THEN (SELECT (CASE WHEN DIVIDEMULTIPLICA = 'M' THEN ((A.QTDNEG*QUANTIDADE)*MULTIPVLR) ELSE TRUNC(((A.QTDNEG/QUANTIDADE)*MULTIPVLR),3) END)
                      FROM TGFVOA VOA WHERE VOA.CODVOL ='LT' AND A.CODPROD = VOA.CODPROD)
           WHEN E.CODVOL != 'KG' AND E.PESOLIQ = 0 AND EXISTS (SELECT * FROM TGFVOA VOA WHERE VOA.CODVOL ='KG' AND A.CODPROD = VOA.CODPROD)
                THEN (SELECT (CASE WHEN DIVIDEMULTIPLICA = 'M' THEN ((A.QTDNEG*QUANTIDADE)*MULTIPVLR) ELSE TRUNC(((A.QTDNEG/QUANTIDADE)*MULTIPVLR),3) END)
                      FROM TGFVOA VOA WHERE VOA.CODVOL ='KG' AND A.CODPROD = VOA.CODPROD)
           ELSE A.QTDNEG
      END),0) AS QTD_UN_PADRAO,
    COALESCE((
      CASE WHEN E.CODVOL IN ('LT','KG') THEN A.QTDNEG
           WHEN E.PESOLIQ != 0 THEN E.PESOLIQ * QTDNEG
           WHEN E.CODVOL != 'LT' AND E.PESOLIQ = 0 AND EXISTS (SELECT * FROM TGFVOA VOA WHERE VOA.CODVOL ='LT' AND A.CODPROD = VOA.CODPROD)
                THEN (SELECT (CASE WHEN DIVIDEMULTIPLICA = 'M' THEN ((A.QTDNEG*QUANTIDADE)*MULTIPVLR) ELSE TRUNC(((A.QTDNEG/QUANTIDADE)*MULTIPVLR),3) END)
                      FROM TGFVOA VOA WHERE VOA.CODVOL ='KG' AND A.CODPROD = VOA.CODPROD)
           ELSE A.QTDNEG
      END),0) AS QTD_CONVERTIDO_KG,
    '1' AS CODMODAL_SIMP,
    '0' AS COD_OLEODUTO,
    (CASE WHEN D.AD_CODINSTALACAO_ANP IS NULL THEN D.CGC_CPF ELSE '0' END) AS CNPJ_PARC,
    (CASE WHEN (D.AD_CODINSTALACAO_ANP IS NULL OR COALESCE(E.AD_TEM_COLETA,'N') = 'S')
          THEN COALESCE((SELECT CID.AD_CODCID_ANP FROM TSICID CID WHERE CID.CODCID = D.CODCID),'0')
          ELSE '0' END) AS CODCID_ANP,
    (CASE WHEN  (D.AD_CODINSTALACAO_ANP IS NULL AND D.CGC_CPF IS NOT NULL)
          THEN COALESCE(D.AD_CNAE_ANP,'0') ELSE '0' END) AS AD_CNAE_ANP,
    (CASE WHEN (SELECT CODOPER_ANP FROM AD_OPERACAOANP ANP WHERE ANP.CODOPER = C.AD_CODOPERANP) IN ('2011001','2012001')
          THEN (SELECT AD_CODPAI_ANP FROM TSICID CID
                  INNER JOIN TSIUFS UF ON CID.UF = UF.CODUF
                  INNER JOIN TSIPAI PAI ON UF.CODPAIS = PAI.CODPAIS
                WHERE D.CODCID = CID.CODCID)
          ELSE '0' END) AS COD_PAIS_ANP,
    COALESCE(B.AD_LICENCA_IMPORTACAO_LI,'0') AS LICENCA_IMPORTACAO_LI,
    COALESCE(AD_NUM_DELCARACAO_IMPORT_DI,'0') AS NUM_DELCARACAO_IMPORTACAO_DI,
    '0' AS NRONF,
    (CASE WHEN (CASE WHEN B.CHAVENFE IS NOT NULL THEN B.CHAVENFE ELSE B.CHAVECTE END) IS NULL
          THEN COALESCE((SELECT SER.COD_SIMP FROM AD_SERIENFOPERSIMP SER WHERE SER.CODSEROPER = B.AD_CODSEROPER),'0')
          ELSE '0' END) AS COD_SERIE_NF,
    (CASE WHEN B.DTENTSAI IS NOT NULL THEN TO_CHAR(B.DTENTSAI, 'DDMMYYYY') ELSE '0' END) AS DTENTSAI,
    '0' AS COD_TIP_TAR_SERV,
    '0' AS CARACTERISTICA_INATIVO,
    '0' AS METODO_INATIVO,
    (CASE WHEN CIF_FOB = 'C' THEN 10
          WHEN CIF_FOB = 'F' THEN 11
          WHEN CIF_FOB = 'T' THEN 12
          WHEN CIF_FOB = 'R' THEN 13
          WHEN CIF_FOB = 'D' THEN 14
          WHEN CIF_FOB = 'S' THEN 19
          ELSE 19 END) AS MODALIDADE_FRETE,
    '0' AS VALOR_CARACTERISTICA,
    COALESCE(E.CODANP,0) AS CODPROD_RESULTANTE_ANP,
    COALESCE(A.VLRUNIT,100) AS VLRUNIT,
    '0' AS RECIPIENTE_GLP,
    (CASE WHEN B.CHAVENFE IS NOT NULL THEN B.CHAVENFE ELSE B.CHAVECTE END) AS CHAVE_NFE_CTE,
    (CASE WHEN D.AD_CODINSTALACAO_ANP IS NOT NULL THEN C.AD_CODOPERTOTALIZADORANP ELSE AD_CODOPERANPAGENTENREGULADOTOT END) AS OPER_TOTALIZADOR
  FROM TGFITE A
  INNER JOIN TGFCAB B ON A.NUNOTA = B.NUNOTA
  INNER JOIN TGFTOP C ON B.CODTIPOPER = C.CODTIPOPER
    AND C.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP TOP WHERE C.CODTIPOPER = TOP.CODTIPOPER)
  INNER JOIN TGFPAR D ON B.CODPARC = D.CODPARC
  INNER JOIN TGFPRO E ON A.CODPROD = E.CODPROD
  INNER JOIN TSIEMP F ON B.CODEMP = F.CODEMP
  WHERE COALESCE(C.AD_ATUALIZA_EST_SIMP,'N') = 'S'
    AND COALESCE(E.AD_GERA_SIMP,'N') = 'S'
    AND B.STATUSNOTA = 'L'
    AND B.TIPMOV != 'F'
    AND TO_CHAR(B.DTNEG,'mm-yyyy') = ?
    AND B.CODEMP = ?
    AND COALESCE(B.STATUSNFE,'R') = (CASE WHEN B.TIPMOV = 'C' THEN COALESCE(B.STATUSNFE,'R') ELSE 'A' END)
    AND A.NUNOTA || '-' || A.SEQUENCIA NOT IN (
      SELECT VAR.NUNOTAORIG || '-' || VAR.SEQUENCIAORIG
      FROM TGFVAR VAR
      INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
      INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
        AND TOP.DHALTER = (SELECT MAX(TOP2.DHALTER) FROM TGFTOP TOP2 WHERE TOP.CODTIPOPER = TOP2.CODTIPOPER)
      WHERE COALESCE(TOP.AD_CANCELA_SIMP,'N') = 'S'
    )
)
GROUP BY
  NUNOTA, AD_TEM_COLETA, OPER_PAD_DISP_COLETA, CLASS_OPERACAO, OPERACAO, AD_CODEMP_ANP, COD_INST_EMP, COD_INST_PAR,
  CODPROD_ANP, CODMODAL_SIMP, COD_OLEODUTO, CNPJ_PARC, CODCID_ANP, AD_CNAE_ANP, COD_PAIS_ANP,
  LICENCA_IMPORTACAO_LI, NUM_DELCARACAO_IMPORTACAO_DI, NRONF, COD_SERIE_NF, DTENTSAI, COD_TIP_TAR_SERV,
  CARACTERISTICA_INATIVO, METODO_INATIVO, MODALIDADE_FRETE, VALOR_CARACTERISTICA, CODPROD_RESULTANTE_ANP,
  VLRUNIT, RECIPIENTE_GLP, CHAVE_NFE_CTE, OPER_TOTALIZADOR
