INSERT INTO AD_DETSIMULARSIMP (
  CODSIMSIM, CODDETSIMSIMP, NUNOTA, IDIPROC, CODEMP_ANP, MESREFERENCIA, CODOPER, CODINSTALACAO1,
  CODINSTALACAO2, CODPROD_ANP, QTD_PROD_UN_ANP, QTD_PROD_OPERADO_KG, COD_MODAL_MOVIMENTACAO,
  COD_OLEODUTO_TRANSPORTE, CNPJ_PARC, CODCID_ANP, COD_ATIV_PARC_ANP, CODPAIS_ANP, NUM_LICEN_IMPORT,
  NUM_DECLARACAO_IMPORT, NUMNF, SERIE_NF, DAT_OPER_COMERCIAL, COD_TIP_TARIFA_SERVICO, CARACTERISTICA,
  METODO, MODALIDADE_FRETE, NUM_DOC_QUALIDADE, COD_OPER_RESULTANTE, VLRUNIT_NF, RECEPIENTE_GLP,
  CAHVE_NFE_CTE, OPERTOTALIZADOR
)
(
SELECT
  ? AS CODSIMSIM,
  (SELECT COALESCE(MAX(CODDETSIMSIMP),0) FROM AD_DETSIMULARSIMP WHERE CODSIMSIM = ?) + ROWNUM AS CODDETSIMSIMP,
  NUNOTA,
  IDIPROC,
  AD_CODEMP_ANP AS CODEMP_ANP,
  REPLACE(?, '-', '') AS MESREFERENCIA,
  OPERACAO AS CODOPER,
  COD_INST_EMP AS CODINSTALACAO1,
  COD_INST_PAR AS CODINSTALACAO2,
  CODPROD_ANP AS CODPROD_ANP,
  CASE WHEN ROUND(SUM(QTD_UN_PADRAO),0) = 0 THEN 1 ELSE ROUND(SUM(QTD_UN_PADRAO),0) END AS QTD_PROD_UN_ANP,
  CASE WHEN ROUND(SUM(QTD_CONVERTIDO_KG),0) = 0 THEN 1 ELSE ROUND(SUM(QTD_CONVERTIDO_KG),0) END AS QTD_PROD_OPERADO_KG,
  CODMODAL_SIMP AS COD_MODAL_MOVIMENTACAO,
  COD_OLEODUTO AS COD_OLEODUTO_TRANSPORTE,
  CNPJ_PARC AS CNPJ_PARC,
  CODCID_ANP AS CODCID_ANP,
  AD_CNAE_ANP AS COD_ATIV_PARC_ANP,
  COD_PAIS_ANP AS CODPAIS_ANP,
  REPLACE(REPLACE(LICENCA_IMPORTACAO_LI,'-',''),'/','') AS NUM_LICEN_IMPORT,
  REPLACE(REPLACE(NUM_DELCARACAO_IMPORTACAO_DI,'-',''),'/','') AS NUM_DECLARACAO_IMPORT,
  NRONF AS NUMNF,
  COD_SERIE_NF AS SERIE_NF,
  DTENTSAI AS DAT_OPER_COMERCIAL,
  COD_TIP_TAR_SERV AS COD_TIP_TARIFA_SERVICO,
  CARACTERISTICA_INATIVO AS CARACTERISTICA,
  METODO_INATIVO AS METODO,
  MODALIDADE_FRETE AS MODALIDADE_FRETE,
  VALOR_CARACTERISTICA AS NUM_DOC_QUALIDADE,
  CODPROD_RESULTANTE_ANP AS COD_OPER_RESULTANTE,
  VLRUNIT AS VLRUNIT_NF,
  RECEPIENTE_GLP AS RECEPIENTE_GLP,
  CHAVE_NFE_CTE AS CAHVE_NFE_CTE,
  OPER_TOTALIZADOR AS OPERTOTALIZADOR
FROM (
  /* Mesma lógica da sua função producaoMp; apenas parametrizado */
  /* Dentro do bloco, use TO_CHAR(B.DTNEG,'mm-yyyy') = ? e B.CODEMP = ? */
)
GROUP BY
  NUNOTA, IDIPROC, AD_CODEMP_ANP, OPERACAO, COD_INST_EMP, COD_INST_PAR, CODPROD_ANP,
  CODMODAL_SIMP, COD_OLEODUTO, CNPJ_PARC, CODCID_ANP, AD_CNAE_ANP, COD_PAIS_ANP,
  LICENCA_IMPORTACAO_LI, NUM_DELCARACAO_IMPORTACAO_DI, NRONF, COD_SERIE_NF, DTENTSAI, COD_TIP_TAR_SERV,
  CARACTERISTICA_INATIVO, METODO_INATIVO, MODALIDADE_FRETE, VALOR_CARACTERISTICA, CODPROD_RESULTANTE_ANP,
  VLRUNIT, RECEPIENTE_GLP, CHAVE_NFE_CTE, OPER_TOTALIZADOR
)
