SELECT
  CODSIMSIM,
  STATUS,
  (LPAD(MES_REFERENCIA,2,0) || '-' || ANO_REFRENCIA) AS REFERENCIA
FROM AD_SIMULARSIMP
WHERE STATUS IN ('1','2')
  AND (LPAD(MES_REFERENCIA,2,0) || '-' || ANO_REFRENCIA) = ?
