SELECT
   TO_CHAR(COALESCE(E.CODANP, 0))       AS CODPROD_ANP,
   SUM(COALESCE(I.QTD_CONVERTIDO_KG,0)) AS QTD_CONVERTIDO_KG,
   '1'                                  AS CODMODAL_SIMP,
   CAB.DTNEG                            AS DTNEG,
   REGEXP_REPLACE(PAR.CGC_CPF,'[^0-9]','') AS CNPJ_PARC,
   EMP.UF AS UF_EMP
FROM TGFCAB CAB
JOIN TGFITE I   ON I.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFPRO E ON E.CODPROD = I.CODPROD
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
WHERE CAB.CODEMP = :CODEMP
  AND CAB.DTNEG >= :DTINI
  AND CAB.DTNEG <  :DTFIM
  AND CAB.TIPMOV = 'V'
GROUP BY TO_CHAR(COALESCE(E.CODANP, 0)), CAB.DTNEG, PAR.CGC_CPF, EMP.UF
